language: rust

branches:
  only:
  - gh-pages

script:
  - ./build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages

env:
  global:
    secure: FFifLxLftvj3678H1P+SRfRIx6QkhECQKrLYkGU5MmC8M2A+Aeh/STpI0veek6JO7NV/VxxaNcHmXGSNk8LFhuAlt3MJndFr28j7AfY9V9gV+0dA39Ohgpl+7MHI1zCYUcETB5hY8/5Abab2skNe25xtn2qmEqvsMKwBzawAzGfSQO6risv/ASobeUCXW5qup3wMyHKaRRZ/puu2DlXwPb0gycofVqqdbo8KPEsgKI9rYugNhL6ShHddR9rv+LCj4G64E7ZVXMdC+dctKonHvUm3KVNcWSItmTKRzIX9wOE9AIDrBf7fSTsutIcLBXy3wswm017UblB35kAX3Y+njzWF0qWszRpC4x1a6Un46ft+kTD3w4DcqWZ6FOerADXpZTUulxXZUrkIGt3+oNVy2GbUcE4DEu2YGo6ky00qQwbESjDVTbgMdQn/dMAtdZ9o19JBYGaMHC3WmC2MGIh3nAL4zy1caLlFQC04v+sk255U27hc0KjjCKQT8tVuCu2gLjV4suM2EBBxntUoCv5Y4k1ei4Fuzvq9Fw2rV7efeAnOCtHBCvBCyhGO3hnu4efjm+1jCzRCVb8hUZlqSuw0Ou8YPDai9vz+Z3pSzBmdMHcd+UNSa9R/Q5CSDAvUKqY1t9mibT3GRG7Zp8B1Te4J0uTQGJpX0zUee3xKHBP4bMs=

notifications:
  email: false
